language: cpp
dist: bionic
compiler: gcc

script:
  - $TRAVIS_BUILD_DIR/script/configure.sh
  - $TRAVIS_BUILD_DIR/script/gen-ast.sh
  - $TRAVIS_BUILD_DIR/script/build.sh
  - pushd $TRAVIS_BUILD_DIR && ./tool/run-test.py && popd